spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: ${moovin.datasource.url}
    username: ${moovin.datasource.user}
    password: ${moovin.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver